name: "publish to npm"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-to-npm:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: |
          wget --no-check-certificate  https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v1.0.4/aptos-cli-1.0.4-Ubuntu-22.04-x86_64.zip
          unzip aptos-cli-1.0.4-Ubuntu-22.04-x86_64.zip
          chmod +x aptos
          cp aptos /usr/local/bin
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Compile
        run: |
          bash ./aptos/build.sh
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
